export enum LockEnum {
  PRICE_ORACLE = "PRICE_ORACLE",
  SWAP = "SWAP",
  TRADE = "TRADE",
  P2P = "P2P",
  WALLET = "WALLET",
  AUTH = "AUTH",
  RAFFLE = "RAFFLE",
  NOTIFICATION = "NOTIFICATION",
  CARD = "CARD",
  WALLET_EXCHANGE = "WALLET_EXCHANGE",
  RANDOM = "RANDOM",
}
